'use strict';(function(){function g(b,e){function k(b){return l.source?(b=new q.Promise,b.fulfill(),b):q.IO.load(l.id,b).then(function(b){q.IO.bind(l.id,b);l.source=b},function(){})}function n(){l.ast=e.parse(l.source)}function p(b,d){l.ast.body.filter(function(b,d){return"ImportStatement"==b.type?(s.push(d),!0):!1}).forEach(function(b){b=b.uri.content;if(!(null===l.id||"/"==b[0])){var d=l.id.split("/").slice(0,-1).join("/");d?("/"==d[d.length-1]&&(d=d.slice(0,d.length-1)),b=d+"/"+b):b="./"+b}b=new g(b,
e);l.resources.push(b)});var k=[];l.resources.forEach(function(e){k.push(e.build(b,d))});return q.Promise.all(k)}function E(){for(var b=l.resources.length-1;0<=b;b--)Array.prototype.splice.apply(l.ast.body,[s[b]||0,1].concat(l.resources[b].ast.body));l.isReady=!0}var l=this;this.id=b;this.resources=[];this.source=null;this.isReady=!1;this.ast={type:"LOL",body:[]};this.build=function(b,e){if(7<=b)throw new d("Too many nested imports.");return k(e).then(n).then(p.bind(this,b+1,e)).then(E)};this.fetch=
k;this.parse=n;this.buildImports=p;this.flatten=E;var s=[]}function e(b,d,e){function k(b){var d=[];l.resources.forEach(function(e){d.push(e.build(0,b))});return q.Promise.all(d)}function n(){l.ast.body=l.resources.reduce(function(b,d){return b.concat(d.ast.body)},l.ast.body)}function g(){l.entries=e.compile(l.ast);l.isReady=!0}this.id=b;this.resources=[];this.entries=null;this.ast={type:"LOL",body:[]};this.isReady=!1;this.build=function(b){return k(b).then(n).then(g)};this.getEntry=function(b){if(this.entries.hasOwnProperty(b))return this.entries[b]};
var l=this}function k(b){function k(a,f,c){for(var b={},d=0,e;e=a[d];d++)b[e]=v(e,f);c(b)}function v(a,f,c){return C(a,f,c,!0)}function C(a,f,c,b){if(y){for(var e,k,l=0;k=0==u.length-l?w:D[u[l]];){k.isReady||k.build(!1);var r=k.getEntry(a);if(void 0===r){var g=new p("Entity not found",a,k.id);A.emit("error",g);l++}else try{var m=(b?r.getEntity:r.getString).call(r,F.bind(this,f));0<l&&(g=new n("Entity found in a fallback language ",a,u.slice(0,l)),A.emit("error",g));c&&c(m);return m}catch(h){if(h instanceof
q.Compiler.ValueError)g=new p("Unknown reference in entity's value",a,k.id),A.emit("error",g),e||(e=h.source);else if(h instanceof q.Compiler.IndexError)g=new p("Entity couldn't be evaluated to a single string",a,k.id),A.emit("error",g);else throw h;l++}}g=new n("Entity couldn't be retrieved",a,u);A.emit("error",g);m=e?e:a;c&&c(m);return m}if(!c)throw new d("Context not ready");G.push([a,f,c,b])}function F(a){if(!a)return this.data;var f={},c;for(c in this.data)this.data.hasOwnProperty(c)&&(f[c]=
this.data[c]);if(a)for(c in a)a.hasOwnProperty(c)&&(f[c]=a[c]);return f}function E(a,f){if("function"===typeof a)for(var c in D){var b=D[c],k=new g(a(c),x);b.resources.push(k);if("function"===typeof f)q.IO.bind(a(c),f(c));else if(void 0!==f)throw new d("Arguments to bindResource must be of the same type");}else if(void 0===w&&(w=new e(null,x,B)),c=new g(a,x),w.resources.push(c),"string"===typeof f)q.IO.bind(a,f);else if(void 0!==f)throw new d("Arguments to bindResource must be of the same type");
}function l(){y=!0;A.emit("ready")}function s(a){A.emit("error",a)}this.id=b;this.data={};this.addResource=function(a){if(0===u.length)w=new e(null,x,B);else throw new d("Can't use addResource with registered languages");var f=new g(null,x);f.source=a;w.resources.push(f)};this.linkResource=function(a){E(a)};this.bindResource=E;this.registerLocales=function(){for(var a in arguments){var f=arguments[a];u.push(f);D[f]=new e(f,x,B)}};this.freeze=function(){return(0<u.length?D[u[0]]:w).build(!0).then(l)};
this.get=function(a,f,c){return C(a,f,c,!1)};this.getEntity=v;this.localize=function(a,f,c){y?k(a,f,c):this.addEventListener("ready",function(){k(a,f,c)})};this.addEventListener=function(a,f){A.addEventListener(a,f)};this.removeEventListener=function(a,f){A.removeEventListener(a,f)};var u=[],D={},w,y=!1,A=new q.EventEmitter,x=new q.Parser(q.EventEmitter),B=new q.Compiler(q.EventEmitter,q.Parser),G=[];this.addEventListener("ready",function(){for(;G.length;){var a=G.shift();return C.apply(this,a)}}.bind(this));
x.addEventListener("error",s);B.addEventListener("error",s);B.setGlobals({get hour(){return(new Date).getHours()}})}function d(b){this.name="ContextError";this.message=b}function p(b,e,k){d.call(this,b);this.name="EntityError";this.id=e;this.lang=k;this.message="["+k+"] "+e+": "+b}function n(b,e,k){d.call(this,b);this.name="GetError";this.id=e;this.tried=k;this.message=k.length?e+": "+b+"; tried "+k.join(", "):e+": "+b}var q={Context:k,getContext:function(b){return new k(b)}};k.Error=d;k.EntityError=
p;d.prototype=Object.create(Error.prototype);d.prototype.constructor=d;p.prototype=Object.create(d.prototype);p.prototype.constructor=p;n.prototype=Object.create(d.prototype);n.prototype.constructor=n;this.L20n=q}).call(this);
(function(){var g=function(){this._state=0;this._value=null;this._cb={fulfilled:[],rejected:[]};this._thenPromises=[]};g.all=function(e){function k(){p--;0==p&&d.fulfill()}var d=new g,p=e.length;if(0==p)return d.fulfill(),d;for(var n in e)e[n].then(k);return d};g.prototype.then=function(e,k){this._cb.fulfilled.push(e);this._cb.rejected.push(k);var d=new g;this._thenPromises.push(d);0<this._state&&setTimeout(this._processQueue.bind(this),0);return d};g.prototype.fulfill=function(e){if(0!=this._state)return this;
this._state=1;this._value=e;this._processQueue();return this};g.prototype.reject=function(e){if(0!=this._state)return this;this._state=2;this._value=e;this._processQueue();return this};g.prototype._processQueue=function(){for(;this._thenPromises.length;){var e=this._cb.fulfilled.shift(),k=this._cb.rejected.shift();this._executeCallback(1==this._state?e:k)}};g.prototype._executeCallback=function(e){var k=this._thenPromises.shift();if("function"!=typeof e)1==this._state?k.fulfill(this._value):k.reject(this._value);
else try{var d=e(this._value);d&&"function"==typeof d.then?d.then(function(d){k.fulfill(d)},function(d){k.reject(d)}):k.fulfill(d)}catch(g){k.reject(g)}};this.L20n.Promise=g}).call(this);
(function(){function g(){this._listeners={}}g.prototype.emit=function(){var e=Array.prototype.slice.call(arguments),k=e.shift(),k=this._listeners[k];if(!k||!k.length)return!1;k.forEach(function(d){d.apply(this,e)},this);return!0};g.prototype.addEventListener=function(e,k){this._listeners[e]||(this._listeners[e]=[]);this._listeners[e].push(k);return this};g.prototype.removeEventListener=function(e,k){var d=this._listeners[e].indexOf(k);if(-1===d)return this;listeners.splice(d,1);return this};"undefined"!==
typeof exports?exports.EventEmitter=g:this.L20n?this.L20n.EventEmitter=g:this.L20nEventEmitter=g}).call(this);
(function(){function g(k){function d(){for(var a=[],c,f;;){c=v();f=[];"["===m.charAt(h)&&(++h,b(),f=J(s,"]"));b();if(":"!==m.charAt(h))throw r('Expected ":"');++h;b();c={type:void 0,key:c,value:n(),index:f};c.local="_"===c.key.name.charAt(0);a.push(c);c=q();f=m.charAt(h);if(">"===f)break;else if(!c)throw r('Expected ">"');}return a}function g(a){for(var c=a.length,f=h+c,b=m.indexOf(a,f);-1!==b&&92===m.charCodeAt(b-1)&&92!==m.charCodeAt(b-2);)b=m.indexOf(a,b+c);if(-1===b)throw r("Unclosed string literal");
a=m.slice(f,b);h=b+c;return{type:"String",content:a}}function n(a,c){void 0===c&&(c=m.charAt(h));if("'"===c||'"'===c)return c===m.charAt(h+1)&&c===m.charAt(h+2)?g(c+c+c):g(c);if("{"===c){var f;++h;b();if("}"===m.charAt(h))++h,f={type:"Hash",content:[]};else{var d,t;for(f=[];;){d=!1;if("*"===m.charAt(h)){++h;if(d)throw r("Default item redefinition forbidden");d=!0}t=v();b();if(":"!==m.charAt(h))throw r('Expected ":"');++h;b();t={type:"HashItem",key:t,value:n()};t["default"]=d;f.push(t);b();if(d=","===
m.charAt(h))++h,b();if("}"===m.charAt(h)){++h;break}if(!d)throw r('Expected "}"');}f={type:"Hash",content:f}}return f}if(!a)throw r("Unknown value type");return null}function q(){for(var a=h,c=m.charCodeAt(a);32===c||10===c||9===c||13===c;)c=m.charCodeAt(++h);return h!==a}function b(){for(var a=m.charCodeAt(h);32===a||10===a||9===a||13===a;)a=m.charCodeAt(++h)}function z(){++h;return{type:"VariableExpression",id:v()}}function v(){var a=h,c=a,f=m,b=f.charCodeAt(c);if((97>b||122<b)&&(65>b||90<b)&&95!==
b)throw r("Identifier has to start with [a-zA-Z]");for(b=f.charCodeAt(++a);95<=b&&122>=b||65<=b&&90>=b||48<=b&&57>=b||95===b;)b=f.charCodeAt(++a);h+=a-c;return{type:"Identifier",name:f.slice(c,a)}}function C(a,c){if(!q())throw r("Expected white space");var f=m.charAt(h),t=n(!0,f),e=[];if(null===t)if(">"!==f)e=d();else throw r('Expected ">"');else if(f=q(),">"!==m.charAt(h)){if(!f)throw r('Expected ">"');e=d()}b();++h;return{type:"Entity",id:a,value:t,index:c,attrs:e,local:95===a.name.charCodeAt(0)}}
function F(){var a=m.charCodeAt(h);if(60===a){++h;var c=v(),a=m.charCodeAt(h);if(40===a){if("_"===c.name.charAt(0))throw r('Macro ID cannot start with "_"');++h;a=J(z,")");q();if("{"!==m.charAt(h))throw r('Expected "{"');++h;b();var f=w();b();if("}"!==m.charAt(h))throw r('Expected "}"');++h;b();if(62!==m.charCodeAt(h))throw r('Expected ">"');++h;return{type:"Macro",id:c,args:a,expression:f}}return 91===a?(++h,C(c,J(s,"]"))):C(c,[])}if(47===m.charCodeAt(h)&&42===m.charCodeAt(h+1)){c=h+=2;a=m.indexOf("*/",
c);if(-1===a)throw r("Comment without closing tag");h=a+2;return{type:"Comment",content:m.slice(c,a)}}if("import"===m.slice(h,h+6)){h+=6;if("("!==m.charAt(h))throw r('Expected "("');++h;b();c=g(m.charAt(h));b();if(")"!==m.charAt(h))throw r('Expected ")"');++h;return{type:"ImportStatement",uri:c}}throw r("Invalid entry");}function E(){var a=[];for(b();h<H;){try{a.push(F())}catch(c){if(c instanceof e)I.emit("error",c),a.push(N());else throw c;}h<H&&b()}return{type:"LOL",body:a}}function l(){var a=[];
for(b();h<H;)a.push(F()),h<H&&b();return{type:"LOL",body:a}}function s(){return w()}function u(a,c,f,d){for(var t=d(),e,k;;){e="";b();k=m.charAt(h);if(-1===a[0].indexOf(k))break;e+=k;++h;if(1<a.length)if(k=m.charAt(h),a[1]==k)++h,e+=k;else if(a[2]){--h;break}b();t={type:c,operator:{type:f,token:e},left:t,right:d()}}return t}function D(a,c,f,d){var t=m.charCodeAt(h);if(-1===a.indexOf(t))return d();++h;b();return{type:c,operator:{type:f,token:String.fromCharCode(t)},argument:D(a,c,f,d)}}function w(){var a=
u([["|"],"|",!0],"LogicalExpression","LogicalOperator",y);b();if(63!==m.charCodeAt(h))return a;++h;b();var c=w();b();if(58!==m.charCodeAt(h))throw r('Expected ":"');++h;b();return{type:"ConditionalExpression",test:a,consequent:c,alternate:w()}}function y(){return u([["&"],"&",!0],"LogicalExpression","Logicalperator",A)}function A(){return u([["="],"=",!0],"BinaryExpression","BinaryOperator",x)}function x(){return u([["<",">"],"=",!1],"BinaryExpression","BinaryOperator",B)}function B(){return u([["+",
"-"]],"BinaryExpression","BinaryOperator",G)}function G(){return u([["%"]],"BinaryExpression","BinaryOperator",a)}function a(){return u([["*"]],"BinaryExpression","BinaryOperator",f)}function f(){return u([["/"]],"BinaryExpression","BinaryOperator",c)}function c(){return D([43,45,33],"UnaryExpression","UnaryOperator",L)}function t(a,c){if("ParenthesisExpression"!==a.type&&"CallExpression"!==a.type&&"Identifier"!==a.type&&"ThisExpression"!==a.type)throw r("AttributeExpression must have Identifier, This, Call or Parenthesis as left node");
var f;if(c){b();f=w();b();if("]"!==m.charAt(h))throw r('Expected "]"');++h;return{type:"AttributeExpression",expression:a,attribute:f,computed:!0}}f=v();return{type:"AttributeExpression",expression:a,attribute:f,computed:!1}}function L(){var a;if(40===m.charCodeAt(h)){++h;b();var c={type:"ParenthesisExpression",expression:w()};b();if(41!==m.charCodeAt(h))throw r('Expected ")"');++h;a=c}else a=M();for(;;)if(c=m.charCodeAt(h),46===c||91===c){++h;var f=void 0;if(91===c){b();f=w();b();if("]"!==m.charAt(h))throw r('Expected "]"');
++h;a={type:"PropertyExpression",expression:a,property:f,computed:!0}}else f=v(),a={type:"PropertyExpression",expression:a,property:f,computed:!1}}else if(58===c&&58===m.charCodeAt(h+1))h+=2,91===m.charCodeAt(h)?(++h,a=t(a,!0)):a=t(a,!1);else if(40===c)++h,c=a,b(),a={type:"CallExpression",callee:c,arguments:J(s,")")};else break;return a}function M(){for(var a=h,c=m.charCodeAt(a);47<c&&58>c;)c=m.charCodeAt(++a);if(a>h)return c=h,h=a,{type:"Number",value:parseInt(m.slice(c,a),10)};switch(c){case 39:case 34:case 123:case 91:return n();
case 36:return z();case 64:return++h,{type:"GlobalsExpression",id:v()};case 126:return++h,{type:"ThisExpression"};default:return v()}}function J(a,c){var f;b();if(m.charAt(h)===c)return++h,[];for(var d=[];;)if(d.push(a()),b(),f=m.charAt(h),","===f)++h,b();else if(f===c){++h;break}else throw r('Expected "," or "'+c+'"');return d}function r(a,c){void 0===c&&(c=h);var f=m.lastIndexOf("<",c-1),b=m.lastIndexOf(">",c-1),f=m.slice(b>f?b+1:f,c+10);return new e(a+" at pos "+c+': "'+f+'"',c,f)}function N(){var a=
m.indexOf("<",h),c;if(-1===a)return c={type:"JunkEntry",content:m.slice(h)},h=H,c;c={type:"JunkEntry",content:m.slice(h,a)};h=a;return c}this.parse=function(a){m=a;h=0;H=m.length;return K()};this.parseString=function(a){m=a;h=0;H=m.length;try{var c;var f,d;a=h;for(var t=!1,g=m.indexOf("\\");-1!==g;){f=m.charAt(g+1);if('"'==f||"'"==f||"\\"==f)m=m.substr(0,g)+m.substr(g+1);g=m.indexOf("\\",g+1)}for(g=m.indexOf("{{");-1!==g;)if(92===m.charCodeAt(g-1))m=m.substr(0,g-1)+m.substr(g),g=m.indexOf("{{",g+
2);else{t||(d=[],t=!0);a<g&&d.push({type:"String",content:m.slice(a,g)});h=g+2;b();d.push(w());b();if(125!==m.charCodeAt(h)||125!==m.charCodeAt(h+1))throw r('Expected "}}"');a=g=h+2;g=m.indexOf("{{",g)}t?(a<H&&d.push({type:"String",content:m.slice(a)}),c={type:"ComplexString",content:d}):c={type:"String",content:m};return c}catch(l){throw k&&l instanceof e&&I.emit("error",l),l;}};this.addEventListener=function(a,c){if(!I)throw Error("Emitter not available");return I.addEventListener(a,c)};this.removeEventListener=
function(a,c){if(!I)throw Error("Emitter not available");return I.removeEventListener(a,c)};var m,h,H,I,K;k?(I=new k,K=E):K=l}function e(e,d,g){this.name="ParserError";this.message=e;this.pos=d;this.context=g}g.Error=e;e.prototype=Object.create(Error.prototype);e.prototype.constructor=e;"undefined"!==typeof exports?exports.Parser=g:this.L20n?this.L20n.Parser=g:this.L20nParser=g}).call(this);
(function(){function g(b,e){function g(a,f,c,b){a=new a(f,c,b);y&&y.emit("error",a);return a}function C(a){this.id=a.id.name;this.local=a.local||!1;this.index=[];this.attributes={};var f;for(f=0;f<a.index.length;f++)this.index.push(l(a.index[f],this));for(f=0;f<a.attrs.length;f++){var c=a.attrs[f];this.attributes[c.key.name]=new F(c,this)}this.value=l(a.value,this,this.index)}function F(a,f){this.key=a.key.name;this.local=a.local||!1;this.index=[];var c;for(c=0;c<a.index.length;c++)this.index.push(l(a.index[c],
this));this.value=l(a.value,f,this.index);this.entity=f}function E(a){this.id=a.id.name;this.local=a.local||!1;this.expression=l(a.expression,this);this.args=a.args}function l(a,f,c){if(!a)return null;if(!G[a.type])throw g("CompilationError","Unknown expression type"+a.type);c&&(c=c.slice());return G[a.type](a,f,c)}function s(a,f,c,b){if(!a||"string"===typeof a||"boolean"===typeof a||"number"===typeof a)return a;if(a._resolve)return a._resolve(c);a=a(f,c);f=a[0];a=a[1];return s(a,f,c)}function u(a,
f){if("-"==a)return function(a){if("number"!==typeof a)throw new d("The unary - operator takes a number",f);return-a};if("+"==a)return function(a){if("number"!==typeof a)throw new d("The unary + operator takes a number",f);return+a};if("!"==a)return function(a){if("boolean"!==typeof a)throw new d("The ! operator takes a boolean",f);return!a};throw g(k,"Unknown token: "+a,f);}function D(a,f){if("=="==a)return function(a,b){if(("number"!==typeof a||"number"!==typeof b)&&("string"!==typeof a||"string"!==
typeof b))throw new d("The == operator takes two numbers or two strings",f);return a==b};if("!="==a)return function(a,b){if(("number"!==typeof a||"number"!==typeof b)&&("string"!==typeof a||"string"!==typeof b))throw new d("The != operator takes two numbers or two strings",f);return a!=b};if("<"==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new d("The < operator takes two numbers",f);return a<b};if("<="==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new d("The <= operator takes two numbers",
f);return a<=b};if(">"==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new d("The > operator takes two numbers",f);return a>b};if(">="==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new d("The >= operator takes two numbers",f);return a>=b};if("+"==a)return function(a,b){if(("number"!==typeof a||"number"!==typeof b)&&("string"!==typeof a||"string"!==typeof b))throw new d("The + operator takes two numbers or two strings",f);return a+b};if("-"==a)return function(a,
b){if("number"!==typeof a||"number"!==typeof b)throw new d("The - operator takes numbers",f);return a-b};if("*"==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new d("The * operator takes numbers",f);return a*b};if("/"==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new d("The / operator takes two numbers",f);if(0==b)throw new d("Division by zero not allowed.",f);return a/b};if("%"==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new d("The % operator takes two numbers",
f);return a%b};throw g(k,"Unknown token: "+a,f);}function w(a,b){if("&&"==a)return function(a,e){if("boolean"!==typeof a||"boolean"!==typeof e)throw new d("The && operator takes two booleans",b);return a&&e};if("||"==a)return function(a,e){if("boolean"!==typeof a||"boolean"!==typeof e)throw new d("The || operator takes two booleans",b);return a||e};throw g(k,"Unknown token: "+a,b);}this.compile=function(a){x={};for(var b={Entity:C,Macro:E},c=0,d;d=a.body[c];c++){var e=b[d.type];if(e)try{x[d.id.name]=
new e(d)}catch(g){q(g)}}return x};this.setGlobals=function(a){B=a;return!0};this.addEventListener=function(a,b){if(!y)throw Error("Emitter not available");return y.addEventListener(a,b)};this.removeEventListener=function(a,b){if(!y)throw Error("Emitter not available");return y.removeEventListener(a,b)};this.reset=function(){x={};B={};return this};var y=b?new b:null,A=e?new e:null,x={},B;C.prototype._yield=function(a,b){return this.value({__this__:this},a,b)};C.prototype._resolve=function(a){return s(this.value,
{__this__:this},a)};C.prototype.getString=function(a){try{return this._resolve(a)}catch(b){throw q(b),b instanceof p&&y&&y.emit("error",b),b;}};C.prototype.getEntity=function(a){var b={value:this.getString(a),attributes:{}},c;for(c in this.attributes)b.attributes[c]=this.attributes[c].getString(a);return b};F.prototype._yield=function(a,b){return this.value({__this__:this.entity},a,b)};F.prototype._resolve=function(a){return s(this.value,{__this__:this.entity},a)};F.prototype.getString=function(a){try{return this._resolve(a)}catch(b){throw q(b),
b instanceof p&&y&&y.emit("error",b),b;}};E.prototype._call=function(a,b){for(var c={__this__:this},d=0;d<this.args.length;d++)c[this.args[d].id.name]=b[d];return this.expression(c,a)};var G={Identifier:function(a,b){var c=a.name;return function(a,e){if(!x.hasOwnProperty(c))throw new d("Reference to an unknown entry: "+c,b);a.__this__=x[c];return[a,x[c]]}},ThisExpression:function(a,b){return function(a,b){return[a,a.__this__]}},VariableExpression:function(a,b){var c=a.id.name;return function(a,e){if(a.hasOwnProperty(c))return a[c];
if(!e||!e.hasOwnProperty(c))throw new d("Reference to an unknown variable: "+c,b);return[a,e[c]]}},GlobalsExpression:function(a,b){var c=a.id.name;return function(a,e){if(!B)throw new d("Globals missing (tried @"+c+").",b);if(!B.hasOwnProperty(c))throw new d("Reference to an unknown global: "+c,b);return[a,B[c]]}},Number:function(a,b){return function(b,f){return[b,a.value]}},String:function(a,b){var c,d;return function(e,g){if(!d){try{c=A.parseString(a.content)}catch(k){throw new p("Malformed string. "+
k.message,b,a.content);}if("String"==c.type)return[e,c.content];d=l(c,b)}try{return[e,s(d,e,g)]}catch(r){throw q(r),new p(r.message,b,a.content);}}},Hash:function(a,b,c){for(var d=[],e,k=c.length?c.shift():void 0,p=0;p<a.content.length;p++){var r=a.content[p];d[r.key.name]=l(r.value,b,c);r.default&&(e=r.key.name)}return function(a,c,h){h=[h,k,e];for(var l=[],r=0;r<h.length;r++){try{var p=h[r]=s(h[r],a,c)}catch(z){throw q(z),g(n,z.message,b);}if(void 0!==p){if("string"!==typeof p)throw g(n,"Index must be a string",
b);l.push(p);if(d.hasOwnProperty(p))return[a,d[p]]}}throw g(n,l.length?'Hash key lookup failed (tried "'+l.join('", "')+'").':"Hash key lookup failed.",b);}},HashItem:l,ComplexString:function(a,b){for(var c=[],e=0;e<a.content.length;e++)c.push(l(a.content[e],b));return function(){var a=!1;return function(e,g){if(a)throw new d("Cyclic reference detected",b);a=!0;var k=[];try{for(var l=0;l<c.length;l++){var m=s(c[l],e,g);if("string"!==typeof m&&"number"!==typeof m)throw new d("Placeables must be strings or numbers",
b);k.push(m)}}finally{a=!1}return[e,k.join("")]}}()},UnaryExpression:function(a,b){var c=u(a.operator.token,b),d=l(a.argument,b);return function(a,b){return[a,c(s(d,a,b))]}},BinaryExpression:function(a,b){var c=l(a.left,b),d=D(a.operator.token,b),e=l(a.right,b);return function(a,b){return[a,d(s(c,a,b),s(e,a,b))]}},LogicalExpression:function(a,b){var c=l(a.left,b),d=w(a.operator.token,b),e=l(a.right,b);return function(a,b){return[a,d(s(c,a,b),s(e,a,b))]}},ConditionalExpression:function(a,b){var c=
l(a.test,b),e=l(a.consequent,b),g=l(a.alternate,b);return function(a,k){var l=s(c,a,k);if("boolean"!==typeof l)throw new d("Conditional expressions must test a boolean",b);return!0===l?e(a,k):g(a,k)}},CallExpression:function(a,b){for(var c=l(a.callee,b),e=[],g=0;g<a.arguments.length;g++)e.push(l(a.arguments[g],b));return function(a,g){for(var k=[],l=0;l<e.length;l++)k.push(e[l](a,g));l=c(a,g);l=l[1];if(!l._call)throw new d("Expected a macro, got a non-callable.",b);return l._call(g,k)}},PropertyExpression:function(a,
b){var c=l(a.expression,b),e=a.computed?l(a.property,b):a.property.name;return function(a,g){var k=s(e,a,g),l=c(a,g);a=l[0];l=l[1];if(l._yield)return l._yield(g,k);if("function"!==typeof l){if(!l.hasOwnProperty(k))throw new d(k+" is not defined in the context data",b);return[null,l[k]]}return l(a,g,k)}},AttributeExpression:function(a,b){var c=l(a.expression,b),d=a.computed?l(a.attribute,b):a.attribute.name;return function(a,b){var e=s(d,a,b),f=c(a,b);a=f[0];f=f[1];return[a,f.attributes[e]]}},ParenthesisExpression:function(a,
b){return l(a.expression,b)}}}function e(b,d){this.name="CompilerError";this.message=b;this.entry=d.id}function k(b,d){e.call(this,b,d);this.name="CompilationError"}function d(b,d){e.call(this,b,d);this.name="RuntimeError"}function p(b,e,g){d.call(this,b,e);this.name="ValueError";this.source=g}function n(b,e){d.call(this,b,e);this.name="IndexError"}function q(b){if(!(b instanceof e))throw b;}g.Error=e;g.CompilationError=k;g.RuntimeError=d;g.ValueError=p;g.IndexError=n;e.prototype=Object.create(Error.prototype);
e.prototype.constructor=e;k.prototype=Object.create(e.prototype);k.prototype.constructor=k;d.prototype=Object.create(e.prototype);d.prototype.constructor=d;p.prototype=Object.create(d.prototype);p.prototype.constructor=p;n.prototype=Object.create(d.prototype);n.prototype.constructor=n;"undefined"!==typeof exports?exports.Compiler=g:this.L20n?this.L20n.Compiler=g:this.L20nCompiler=g}).call(this);
(function(){this.L20n.Intl={prioritizeLocales:function(g){for(var e={localeMatcher:"lookup"},k=[navigator.language||navigator.userLanguage],d=0,p=k.length,n=void 0;d<p&&void 0===n;){var q=k[d],b=q;a:{for(var n=g,z=b;;){if(-1!==n.indexOf(z)){n=z;break a}var v=z.lastIndexOf("-");if(-1===v){n=void 0;break a}2<=v&&"-"==z[v-2]&&(v-=2);z=z.substr(0,v)}n=void 0}d+=1}k={};if(void 0!==n){if(k.locale=n,q!==b)throw"NotImplemented";}else k.locale="en-US";q=k.locale;if(k.hasOwnProperty("extension"))throw"NotImplemented";
b="-u";for(k=0;0>k;){d=(void 0)(q)[q];p=d[0];n="";if(void 0!==extensionSubtags)throw"NotImplemented";e.hasOwnProperty("key")&&(z=e.key,-1!==d.indexOf(z)&&z!==p&&(n=""),b+=n,k+=1)}2<b.length&&(e=q.substr(0,extensionIndex),q=q.substr(extensionIndex+1),q=e+b+q);e=q;q=g.indexOf(e);if(-1===q)return g;g.splice(q,1);g.unshift(e);return g}}}).call(this);
(function(){var g={};this.L20n.IO={load:function(e,k){var d=new L20n.Promise;if(void 0!==g[e])return d.fulfill(g[e]),d;var p=new XMLHttpRequest;p.overrideMimeType("text/plain");p.addEventListener("load",function(){200==p.status?d.fulfill(p.responseText):d.reject()});p.addEventListener("abort",function(e){return d.reject(e)});p.open("GET",e,k);p.send("");return d},bind:function(e,k){g[e]=k}}}).call(this);
(function(){function g(){n.addEventListener("ready",function(){var b=document.createEvent("Event");b.initEvent("LocalizationReady",!1,!1);document.dispatchEvent(b);document.body?d():document.addEventListener("readystatechange",function(){"interactive"===document.readyState&&d()})});n.addEventListener("error",function(b){b.code&L20n.NOVALIDLOCALE_ERROR&&(b=document.createEvent("Event"),b.initEvent("LocalizationFailed",!1,!1),document.dispatchEvent(b))});n.freeze();HTMLElement.prototype.retranslate=
function(){if(this.hasAttribute("data-l10n-id"))return p(n,this),!0;throw Exception("Node not localizable");}}function e(b){var d=new L20n.Promise;L20n.IO.load(b,!0).then(function(b){var e=JSON.parse(b);b=L20n.Intl.prioritizeLocales(e.languages);n.registerLocales.apply(this,b);n.linkResource(function(b){return e.resources[0].replace("{{lang}}",b)});d.fulfill()});return d}function k(){document.body.style.visibility="visible";var b=document.createEvent("Event");b.initEvent("DocumentLocalized",!1,!1);
document.dispatchEvent(b)}function d(){p(document);HTMLDocument.prototype.__defineGetter__("l10n",function(){return n});k()}function p(b){var d=b.querySelectorAll("[data-l10n-id]");b=[];for(var e=0;e<d.length;e++)b.push(d[e].getAttribute("data-l10n-id"));n.localize(b,{},function(b){for(var e=0;e<d.length;e++){var g=d[e].getAttribute("data-l10n-id");b[g].value&&(d[e].textContent=b[g].value);for(var k in b[g].attributes)d[e].setAttribute(k,b[g].attributes[k])}})}var n=this.L20n.getContext(document.location.host),
q;document.body.style.visibility="hidden";(function(){q=document.head;var b=q.querySelector('script[type="application/l10n-data+json"]');b&&(n.data=JSON.parse(b.textContent));(b=q.querySelector('script[type="application/l20n"]'))?(b.hasAttribute("src")?n.linkResource(b.getAttribute("src")):n.addResource(b.textContent),g()):(b=q.querySelector('link[rel="localization"]'))&&e(b.getAttribute("href")).then(g);return!0})()}).call(this);
